version: '3'
services:
  pachotel_db:
    image: postgres:latest
    container_name: pachotel_db_dbt
    restart: always
    environment:
      - POSTGRES_DB=pachotel_dbt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5435:5432 
